[package]
name = "websocket-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
tokio = {version = "1.43.0", features = ["full"]}
tokio-tungstenite = {version ="0.26.2", features = ["native-tls"]}
